import "./globals.css";


import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

import Desktop from "@/components/layout/navbar/Desktop";
import Mobile from "@/components/layout/navbar/Mobile";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>


        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />



      </head>




      <body >


        <Header />
        <Desktop />
        <div className="hidden show-mobile-nav">
          <Mobile />
        </div>
        <div>
          {children}
        </div>
        <Footer />


      </body>
    </html>
  );
}

